bionicarm:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000
    
    computed_torque_controller:
      type: arm_controllers/Computed_Torque_Controller
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
      gains:
        bionicarm_joint1: 
          pid: {p: 100.0, i: 0, d: 20.0}
        bionicarm_joint2: 
          pid: {p: 100.0, i: 0, d: 20.0}
        bionicarm_joint3: 
          pid: {p: 100.0, i: 0, d: 20.0}
        bionicarm_joint4: 
          pid: {p: 100.0, i: 0, d: 20.0}
        bionicarm_joint5: 
          pid: {p: 100.0, i: 0, d: 20.0}

      root_link: world
      tip_link: hand
